#! /bin/sh
xset +fp /home/suphal/.local/share/fonts &
xset fp rehash &
sxhkd &
picom &
nitrogen --restore &
sh /home/suphal/.config/polybar/launch.sh &
xdo lower -N Polybar &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           2

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config top_padding 22

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a Spotify desktop='^3'
bspc rule -a Code desktop='^4'
bspc rule -a code desktop='^4'
bspc rule -a spotify desktop='^3'
bspc rule -a Pcmanfm desktop='^5'
bspc rule -a zoom desktop='^6'
bspc rule -a mplayer2 state=floating
bspc rule -a Screenkey manage=off
bspc rule -a Lxappearance desktop='^10'
